### ISSUE TITLE
Add custom class

### ISSUE THREAD

**Issue by kumavale** [kumavale/mdbook-embed#3]
### Problem

For example for YouTube, add the `mdbook-embed-youtube` class.

```html
<iframe class="mdbook-embed-youtube" width="560" height="315" src="https://www.youtube.com/embed/d66B35sT1gQ"></iframe>
```

This makes it easier for users to apply their own styles.

```css
/* Embed responsive YouTube videos */
iframe.mdbook-embed-youtube {
    aspect-ratio: 16 / 9;
    height: 100%;
}
```

### Proposed Solution

```diff
- format!("<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/{}\"></iframe>", &cap[1])
+ format!("<iframe class="mdbook-embed-youtube" width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/{}\"></iframe>", &cap[1])
```

### Notes

*No response*
